gazebo_ros_control/pid_gains:
  arm_1_joint_1: {p: 1.0, i: 0.0, d: 1.0}
  arm_1_joint_2: {p: 1.0, i: 0.0, d: 1.0}
  arm_1_joint_3: {p: 1.0, i: 0.0, d: 1.0}
  arm_1_joint_4: {p: 1.0, i: 0.0, d: 1.0}
  arm_1_joint_5: {p: 1.0, i: 0.0, d: 1.0}
  arm_1_gripper_joint: {p: 1.0, i: 0.0, d: 1.0}
  arm_2_joint_1: {p: 1.0, i: 0.0, d: 1.0}
  arm_2_joint_2: {p: 1.0, i: 0.0, d: 1.0}
  arm_2_joint_3: {p: 1.0, i: 0.0, d: 1.0}
  arm_2_joint_4: {p: 1.0, i: 0.0, d: 1.0}
  arm_2_joint_5: {p: 1.0, i: 0.0, d: 1.0}
  arm_2_gripper_joint: {p: 1.0, i: 0.0, d: 1.0}
  head_pan_joint: {p: 1.0, i: 0.0, d: 1.0}
  head_tilt_joint: {p: 1.0, i: 0.0, d: 1.0}
